server:
  tomcat:
    max-http-header-size: 8192
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentoa?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  #设置Email
  mail:
    protocol: smtp
    host: smtp.qq.com
    username: 575612802@qq.com
    password: nmsyqvmdpiazbbga
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#设置mybatis驼峰命名规则
mybatis:
  configuration:
    map-underscore-to-camel-case: true





